In [3]:
import numpy as np

In [8]:
arr = np.arange(1, 11, dtype=int)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
m = np.zeros((3, 3), dtype=int)
m

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
array = np.random.randint(1, 11, size=(5, 5))
array

array([[ 2,  6,  6,  1,  6],
       [ 5,  3,  9,  1,  1],
       [ 7,  1, 10,  5,  4],
       [ 8,  9,  3,  7,  8],
       [ 9,  3,  1,  2,  7]], dtype=int32)

In [15]:
array = np.random.rand(4, 4)
array

array([[0.4804534 , 0.10095326, 0.67740793, 0.53553018],
       [0.86247051, 0.66223081, 0.69942355, 0.46140922],
       [0.08567421, 0.3899401 , 0.9697149 , 0.70743208],
       [0.94259571, 0.42184564, 0.6170777 , 0.99060188]])

In [24]:
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)
sum = a+b
diff = a-b
prod = a*b
print("Масив 1:", a)
print("Масив 2:", b)
print("Додавання масивів:", sum)
print("Віднімання масивів:", diff)
print("Множення масивів:", prod)

Масив 1: [10  8  4  3  1]
Масив 2: [10  3  9  6  1]
Додавання масивів: [20 11 13  9  2]
Віднімання масивів: [ 0  5 -5 -3  0]
Множення масивів: [100  24  36  18   1]


In [25]:
vector1 = np.random.randint(1, 11, size=7)  
vector2 = np.random.randint(1, 11, size=7) 

dot_product = np.dot(vector1, vector2)

print("Вектор 1:", vector1)
print("Вектор 2:", vector2)
print("Скалярний добуток:", dot_product)

Вектор 1: [4 4 4 1 7 4 3]
Вектор 2: [ 7  2  3  5 10 10  5]
Скалярний добуток: 178


In [30]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))

c = np.dot(a, b)

print("Масив 1:\n", a)
print("Масив 2:\n", b)
print("Перемноження масивів:\n", c)

Масив 1:
 [[1 9]
 [6 4]]
Масив 2:
 [[ 1  5  8]
 [ 3 10  6]]
Перемноження масивів:
 [[28 95 62]
 [18 70 72]]


In [37]:
a = np.random.randint(1, 11, size=(3, 3))

if np.linalg.det(a) != 0:
    b = np.linalg.inv(a)
    print("Матриця:\n", a)
    print("Обернена матриця:\n", b)
else:
    print("Матриця не має оберненої, оскільки її визначник дорівнює 0.")

Матриця:
 [[5 6 7]
 [8 5 4]
 [3 1 2]]
Обернена матриця:
 [[-0.13953488  0.11627907  0.25581395]
 [ 0.09302326  0.25581395 -0.8372093 ]
 [ 0.1627907  -0.30232558  0.53488372]]


In [38]:
a = np.random.randint(1, 11, size=(4, 4))
b = a.T
print("Матриця:\n", a)
print("Транспонована матриця:\n", b)

Матриця:
 [[ 1  9  7  9]
 [ 6  6  9  5]
 [ 2  2  3  4]
 [ 2 10  5  9]]
Транспонована матриця:
 [[ 1  6  2  2]
 [ 9  6  2 10]
 [ 7  9  3  5]
 [ 9  5  4  9]]


In [40]:
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=4)
с = np.dot(a, b)
print("Матриця:\n", a)
print("Вектор:\n", b)
print("Результат перемноження матриці і вектора:\n", с)

Матриця:
 [[10  7  3  4]
 [ 8  1  1  9]
 [ 6  3  8  8]]
Вектор:
 [9 5 7 4]
Результат перемноження матриці і вектора:
 [162 120 157]


In [42]:
a = np.random.rand(2, 3)
b = np.random.rand(3)
с = np.dot(a, b)
print("Матриця:\n", a)
print("Вектор:\n", b)
print("Результат перемноження матриці і вектора:\n", с)

Матриця:
 [[0.65748558 0.40385213 0.53826469]
 [0.78919946 0.93368858 0.42901082]]
Вектор:
 [0.7307022  0.78906686 0.65153944]
Результат перемноження матриці і вектора:
 [1.14979317 1.59292996]


In [48]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
с = a * b
print("Матриця 1:\n", a)
print("Матриця 2:\n", b)
print("Результат поелементного перемноження матриць:\n", с)

Матриця:
 [[2 4]
 [5 3]]
Вектор:
 [[ 4 10]
 [ 1  8]]
Результат поелементного перемноження матриць:
 [[ 8 40]
 [ 5 24]]


In [49]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
c = np.dot(a, b)
print("Матриця 1:\n", a)
print("Матриця 2:\n", b)
print("Результат добутку матриць:\n", c)

Матриця:
 [[ 4 10]
 [ 6  1]]
Вектор:
 [[3 5]
 [2 4]]
Результат добутку матриць:
 [[32 60]
 [20 34]]


In [50]:
a = np.random.randint(1, 101, size=(5, 5))
c = np.sum(a)
print("Матриця:\n", a)
print("Сума елементів матриці:\n", c)

Матриця:
 [[ 90   8  86  56  86]
 [  9  11  94  15  87]
 [ 32  66  23 100  59]
 [ 12  54  85  72  73]
 [ 31 100 100  63  93]]
Результат добутку матриць:
 1505


In [51]:
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
с = a - b
print("Матриця 1:\n", a)
print("Матриця 2:\n", b)
print("Різниця матриць:\n", с)

Матриця 1:
 [[1 7 1 7]
 [8 4 5 2]
 [9 5 9 4]
 [6 8 4 3]]
Матриця 2:
 [[ 5 10  8  8]
 [ 6  3  4  7]
 [ 2  1  5  9]
 [ 2  3  9  9]]
Результат поелементного перемноження матриць:
 [[-4 -3 -7 -1]
 [ 2  1  1 -5]
 [ 7  4  4 -5]
 [ 4  5 -5 -6]]


In [52]:
a = np.random.rand(3, 3)
b = np.sum(a, axis=1)
print("Матриця:\n", a)
print("Вектор:\n", b)

Матриця:
 [[0.20721762 0.8309799  0.86712342]
 [0.20643155 0.80242473 0.27984963]
 [0.18729065 0.2517547  0.54016097]]
Вектор:
 [1.90532093 1.28870591 0.97920633]


In [53]:
a = np.random.randint(1, 11, size=(3, 4)) 
b = np.square(a)
print("Матриця :\n", a)
print("Матриця з елементами к квадраті:\n", b)

Матриця 1:
 [[10  8  7  5]
 [ 2  7  2  6]
 [ 1  9  2  1]]
Матриця 2:
 [[100  64  49  25]
 [  4  49   4  36]
 [  1  81   4   1]]


In [54]:
a = np.random.randint(1, 51, size=4)
b = np.sqrt(a)
print("Вектор:\n", a)
print("Вектор з квадратними коренями елементів:\n", b)

Вектор:
 [36 27 13 12]
Вектор з квадратними коренями елементів:
 [6.         5.19615242 3.60555128 3.46410162]
